[workspace]
resolver = "2"
members = ["jamcat", "jamcat_commands", "jamcat_common", "jamcat_core", "jamcat_error", "jamcat_music", "jamcat_utils"]

documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[workspace.package]
homepage = "https://github.com/serenity-rs/serenity"
repository = "https://github.com/serenity-rs/serenity.git"
keywords = ["discord", "bot"]
edition = "2024"

[workspace.dependencies]  
jamcat_core = { path = "jamcat_core" }
jamcat_utils = { path = "jamcat_utils" }
jamcat_commands = { path = "jamcat_commands" }
jamcat_music = { path = "jamcat_music" }
jamcat_common = { path = "jamcat_common" }
jamcat_error = { path = "jamcat_error" }
anyhow = "1.0.98"
dotenv = "0.15.0"
lazy_static = "1.5.0"
poise = { version = "0.6.1"}
rand = "0.9.1"
regex = "1.11.1"
reqwest = { version = "0.12.15", default-features = false, package = "reqwest", features = [
    "blocking",
    "json",
    "multipart",
    "rustls-tls",
    "cookies",
] }
rspotify = "0.14.0"
serenity = { version = "0.12.4", features = ["voice", "reqwest"] }
songbird = { version = "0.5.0", features = [
    "driver",
    "gateway",
    "serenity",
    "rustls",
    "receive",
    "tungstenite",
    "builtin-queue",
] }
symphonia = { version = "0.5.4", features = [
    "all-formats",
    "all-codecs",
    "opt-simd",
] }
sqlx = { version = "0.8.5", features = ["runtime-tokio", "sqlite"] }
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = "2.5.4"
uuid = "1.16.0"
tokio = { version = "1.44.2", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
